void manualMode(int i);
void autoMode(int i, int temp_now, int humidity_now, int co2_now);
void tempUp();
void tempDown();
void tempStay();
void ledOn(int val);
void ledOff();
void fanOn(int val);
void fanOff();
void pumpOn();
void pumpOff();
void buzzerOn();
void buzzerOff();
void pwmControl_begin();